### ISSUE TITLE
Falco under configuration management

### ISSUE THREAD

**Issue by ikoniaris** [draios/falco#115]
Idea: it would be nice to have a Puppet module (or other type of configuration management software "recipe") to deploy and manage falco.

**Comment by mstemm** [comment]
Sounds like a good suggestion. I'm not that familiar with Puppet so I'll have to do some research first.

**Comment by juju4** [comment]
Just submit a RFC for an ansible role
https://github.com/draios/falco/issues/128
https://github.com/juju4/ansible-falco/
