### ISSUE TITLE
lyaml build shall depends upon luajit

### ISSUE THREAD

**Issue by matclab** [draios/falco#130]
On release 0.3.0:

Build of lyaml failed when testing if luajit-prefix/src/luajit is a Lua interpreter.

Adding a dependency upon juajit for lyaml in the CMakeLists.txt allos the compilation to go further

**Comment by matclab** [comment]
Same problem for lyaml depending on libyaml

**Comment by mstemm** [comment]
Thanks--I'll take a look at the dependencies to make sure they are all covered. Of course, if you happen to find them all and can package the changes in a PR I'd be happy to take a look.
