### ISSUE TITLE
install-falco linux script contains MiTM opportunity via curl HTTP

### ISSUE THREAD

**Issue by auraltension** [draios/falco#152]
I don't see a copy of the install script here, but figure it's an ok place to report this.  Please let me know if there is a better place to send this.

Within `install-script` which I have just retrieved from `https://s3.amazonaws.com/download.draios.com/stable/install-falco` I have noticed the following concerning lines:

`curl -s -o /etc/yum.repos.d/draios.repo http://download.draios.com/stable/rpm/draios.repo`

`curl -s -o /etc/apt/sources.list.d/draios.list http://download.draios.com/stable/deb/draios.list`

These are both plaintext requests, which I believe are a poor practice and best avoided when you're installing an application intending to increase your security posture.  

I can verify that the repo files can be retrieved fine via HTTPS from the s3 bucket at for example `https://s3.amazonaws.com/download.draios.com/stable/rpm/draios.repo` and given that the bucket is referenced directly elsewhere in the install script it should be fine to change this line also.

Cheers.

**Comment by auraltension** [comment]
I have also observed the same line being recommended within the [wiki](https://github.com/draios/falco/wiki/How%20to%20Install%20Falco%20for%20Linux)

**Comment by mstemm** [comment]
You're right--the install script should only use https requests. We'll make these changes.

**Comment by mstemm** [comment]
And I've updated the [sysdig](https://github.com/draios/sysdig/wiki/How-to-Install-Sysdig-for-Linux) and [falco](https://github.com/draios/falco/wiki/How-to-Install-Falco-for-Linux) wikis to use https urls.

**Comment by mstemm** [comment]
The fix is in place, but I'll keep the issue open until the next falco release just so I can double-check that the updated install script was copied to download.draios.com.

**Comment by mstemm** [comment]
We've done the falco release and the installer script does indeed only have https:// links now, so closing.
