### ISSUE TITLE
option to test falco rules before applying

### ISSUE THREAD

**Issue by juju4** [draios/falco#194]
To test configuration, you can use 'falco -c %s -L'.
ansible has a validate option to test a new file before replacing old one. it works fine for falco.yaml but not to falco_rules.yaml.

it would be nice if 'falco -c %s -L' could also apply to rules file alone or have another option to do so.
it allows play to gracefully fail when there is an error in rules.

it also means you can update falco.yaml, validate, update falco rules and at next play falco.yaml validation will fail because of rules file.

Thanks

**Comment by mstemm** [comment]
Sounds like a great idea, I'll make sure it happens in the next falco release.

**Comment by mstemm** [comment]
I just tried and `falco -L` does validate the contents of the rules file in addition to the configuration file. This is a somewhat recent change, in 0.5.0, as a part of https://github.com/draios/falco/pull/150 and https://github.com/draios/falco/pull/151.

So I think that should be sufficient. If you're looking for the ability to *only* validate falco_rules.yaml go ahead and reopen and I'll add that ability.

**Comment by juju4** [comment]
yes, it's more the latter: only validate falco_rules.yaml
it doesn't seem that I can reopen myself.

**Comment by mstemm** [comment]
Ah ok, I'll reopen then.
