### ISSUE TITLE
Installing Falco from Source on ubuntu

### ISSUE THREAD

**Issue by f5babu** [draios/falco#230]
I am getting the following error while compiling.

In file included from /home/babu/sysdig/src/falco-dev/userspace/engine/falco_engine.cpp:27:0:
/home/babu/sysdig/src/falco-dev/userspace/engine/formats.h:49:9: error: ‘sinsp_evt_formatter_cache’ does not name a type
  static sinsp_evt_formatter_cache *s_formatters;
         ^
userspace/engine/CMakeFiles/falco_engine.dir/build.make:110: recipe for target 'userspace/engine/CMakeFiles/falco_engine.dir/falco_engine.cpp.o' failed
make[2]: *** [userspace/engine/CMakeFiles/falco_engine.dir/falco_engine.cpp.o] Error 1
CMakeFiles/Makefile2:869: recipe for target 'userspace/engine/CMakeFiles/falco_engine.dir/all' failed
make[1]: *** [userspace/engine/CMakeFiles/falco_engine.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

Please let me know how to fix this issue. I am unable to locate the definition of the type for sinsp_evt_formatter_cache.

**Comment by f5babu** [comment]
I also tried to compile falco release 0.6.0 (falco-0.6.0.tar.gz) and I am getting same error.

In file included from /home/babu/sysdig/src/falco/userspace/engine/falco_engine.cpp:27:0:
/home/babu/sysdig/src/falco/userspace/engine/formats.h:49:9: error: ‘sinsp_evt_formatter_cache’ does not name a type
  static sinsp_evt_formatter_cache *s_formatters;
         ^
userspace/engine/CMakeFiles/falco_engine.dir/build.make:110: recipe for target 'userspace/engine/CMakeFiles/falco_engine.dir/falco_engine.cpp.o' failed
make[2]: *** [userspace/engine/CMakeFiles/falco_engine.dir/falco_engine.cpp.o] Error 1
CMakeFiles/Makefile2:869: recipe for target 'userspace/engine/CMakeFiles/falco_engine.dir/all' failed
make[1]: *** [userspace/engine/CMakeFiles/falco_engine.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mstemm** [comment]
`sinsp_evt_formatter_cache` was added to sysdig fairly recently (https://github.com/draios/sysdig/commit/03ad5cfe958fd2d35fee1a3001148fa7b92da5f3). What version of the sysdig repository are you using?

**Comment by f5babu** [comment]
I am using falco release 0.6.0 (falco-0.6.0.tar.gz). I have also tried by downloading falco-dev from https://github.com/draios/falco. In both cases I am getting the same error.

Thanks.
Babu

**Comment by mstemm** [comment]
To compile falco you also need a copy of the sysdig repository (https://github.com/draios/sysdig) checked out as a sibling of the falco directory. I was wondering what version of that sysdig repository you had checked out.

Just in case you didn't see this page, we do have some notes on compiling from source at https://github.com/draios/falco/wiki/How-to-Install-Falco-from-Source.

**Comment by f5babu** [comment]
Thanks, Mark. I am using sysdig-0.15.0. sysdig and falco are parallel directories. I am unable to locate the definition of the type for sinsp_evt_formatter_cache in the source code. I followed notes on compiling from source at https://github.com/draios/falco/wiki/How-to-Install-Falco-from-Source to compile falco.


drwxr-xr-x 13 babu babu 4096 Mar 31 17:49 sysdig-0.15.0
lrwxrwxrwx  1 babu babu   14 Apr  1 23:06 sysdig -> sysdig-0.15.0/
drwxr-xr-x 10 babu babu 4096 Apr  1 23:17 falco-dev
lrwxrwxrwx  1 babu babu   12 Apr  2 08:32 falco -> falco-0.6.0/
drwxrwxr-x 10 babu babu 4096 Apr  2 08:32 falco-0.6.0

Thanks.
Babu

**Comment by mstemm** [comment]
Ok, that explains it. That formatter cache was added after sysdig 0.15.0. You can either check out the head of the dev branch of sysdig, or to get exactly what was used for falco 0.6.0 you can check out the https://github.com/draios/sysdig/tree/falco/0.6.0 tag.

I added a paragraph to the building from source wiki page about the tags we use. Hopefully that will clear up the confusion in the future.

**Comment by f5babu** [comment]
Thanks, Mark. I will try it out and if it works, I will close this issue.

**Comment by f5babu** [comment]
Thanks, Mark. I am able to build falco-0.6.0 successfully with sysdig-0.15.1.
