### ISSUE TITLE
K8S example does not work on Google Container Engine

### ISSUE THREAD

**Issue by mmmeff** [draios/falco#267]
When deploying the DaemonSet yaml to my GKE cluster, the pods are failing to start. Logs:

```
* Setting up /usr/src links from host
ls: cannot access '/host/usr/src': No such file or directory
* Unloading falco-probe, if present
* Running dkms autoinstall
rmmod: ERROR: Module falco_probe is not currently loaded
Error! echo
Your kernel headers for kernel 4.4.21+ cannot be found at
/lib/modules/4.4.21+/build or /lib/modules/4.4.21+/source.
* Trying to load a system falco-probe, if present
* Trying to load a dkms falco-probe, if present
* Trying to find precompiled falco-probe for 4.4.21+
Cannot find kernel config
Mon Aug 21 19:34:07 2017: Falco initialized with configuration file /etc/falco.yaml
Mon Aug 21 19:34:07 2017: Parsed rules from file /etc/falco_rules.yaml
Mon Aug 21 19:34:07 2017: Unable to load the driver. Exiting.
Mon Aug 21 19:34:07 2017: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco-probe module is loaded.. Exiting.
```

I'm sure this is because of the minor differences Google imparts on K8S clusters, but I'm not entirely sure where to start in resolving this.

**Comment by luca3m** [comment]
probably you are using GKE *container optimized* image. That image does not allow to load custom kernel modules. Falco is supported only on Ubuntu images for Google Cloud Platform

**Comment by mstemm** [comment]
Agreed, this is likely the problem. If you're still running into this problem with the ubuntu image, please let us know. Closing for now.

**Comment by hawksight** [comment]
Just out of interest, does falco run on minikube? I can't seem to get it to run.
I get the same error as originally posted on this issue.

If it only works with ubuntu based k8s clusters, perhaps its worth a small note at the top of [this](https://github.com/draios/falco/wiki/How-to-Install-Falco-using-Containers-and-or-Orchestration#container-install-k8s) section noting that; might save people a bit of time.

**Comment by mstemm** [comment]
It's almost the same issue. If I recall, the vm used by minikube doesn't include kernel headers, so falco can't build the kernel module. And the kernel itself isn't a standard one so we can't build a precompiled kernel module easily.

I updated the wiki with a note to make this more clear.
