### ISSUE TITLE
Typo in falco_rules.yaml

### ISSUE THREAD

**Issue by dseevr** [draios/falco#271]
`ansible-playboo` -> `ansible-playbook`

I would have sent a PR, but I don't want to post my real email to agree to the CLA.  ☹️

**Comment by mstemm** [comment]
If you're referring to program names in falco_rules.yaml, this is intentional--the kernel+sysdig truncate program names at 16 characters (15 + trailing null). We use the truncated names so they match.

If this was somewhere else, let me know and reopen.
