### ISSUE TITLE
Please, what's the status regarding lxc/lxd support?

### ISSUE THREAD

**Issue by laymonk** [draios/falco#273]
* Is lxd/lxc supported ?
* how to use?  Any docs?

I have seen #203 .. but it doesn't answer these questions

Thanks in advance

**Comment by mstemm** [comment]
lxc containers should be supported like any other container format. There isn't anything special you have to do to detect lxc containers.

There aren't any specific rule changes for containers running under lxd, but in general we've tried to improve coverage for administrative systems like ansible, etc.

If you have specific problems or false positives, definitely let us know and we can address them.
