### ISSUE TITLE
Optimization that search for evt.type conditionals doesn't work well with nesting

### ISSUE THREAD

**Issue by mattpag** [draios/falco#280]
To replicate, just put all the `evt.type` conditionals of a rule around parenthesis. The optimization check will not find them and complain with a warning.

**Comment by mstemm** [comment]
I couldn't replicate this. I tried a rule like this:

```
- rule: Launch Disallowed Container
  desc: >
    Detect the initial process started by a container that is not in a list of allowed containers.
  condition: (evt.type=execve) and proc.vpid=1 and container and not allowed_containers
  output: Container started and not in allowed list (user=%user.name command=%proc.cmdline %container.info image=%container.image)
  priority: WARNING
  tags: [container]
```

And I could validate the rules file:

```
$ sudo falco -V falco_rules.yaml -c falco.yaml
Wed Apr  4 19:28:57 2018: Validating rules file(s):
Wed Apr  4 19:28:57 2018:    falco_rules.yaml
Wed Apr  4 19:28:57 2018: Ok
```

Do you remember a way to replicate it?

**Comment by mattpag** [comment]
I tried, but it wasn't able to reproduce it too. Probably I was doing something else wrong.
Let me close this, we can reopen it if we stumble upon the issue again in the future.
