### ISSUE TITLE
/lib/modules can't be read-only

### ISSUE THREAD

**Issue by agilgur5** [draios/falco#294]
```
DKMS: build completed.

falco-probe.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.4.78-k8s/kernel/extra/
mkdir: cannot create directory '/lib/modules/4.4.78-k8s/kernel/extra': Read-only file system
cp: cannot create regular file '/lib/modules/4.4.78-k8s/kernel/extra/falco-probe.ko': No such file or directory

depmod...
```

When I remove the read-only flag, this works fine

**Comment by luca3m** [comment]
those errors are expected since we don't want to make changes to the underlying host. falco will work regardless

**Comment by agilgur5** [comment]
I'm confused... why does it try that if it works regardless and why does it give an error at all then? if it's expected, i would think it would be suppressed then, as otherwise it's extremely misleading and disorienting

**Comment by JPLachance** [comment]
Hello! I am just starting to play with Falco and I lost a couple of minutes trying to find out what was wrong with my setup before finding this issue. If really it's the expected behavior, it should not be displayed as an error. My 2 cents! 😃

**Comment by djsly** [comment]
Came here after trying to see what was wrong with my configuration... missing a `falco-probe.ko` file sounds problematic. 

the least that could be done, augment the logs with 

"this is normal, ignore this error if you system is readonly, or you are running in a container"
