### ISSUE TITLE
Bad return status for module build on kernel

### ISSUE THREAD

**Issue by 97turbotalon** [draios/falco#314]
K8S: 1.8.6 with RBAC
Image: kope.io/k8s-1.8-debian-stretch-amd64-hvm-ebs-2018-01-05
KOPS: 1.8.0
Cloud: AWS

I receive the following error message when the pod is trying to start.

* Setting up /usr/src links from host
* Unloading falco-probe, if present
rmmod: ERROR: Module falco_probe is not currently loaded
* Running dkms autoinstall

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j2 KERNELRELEASE=4.9.0-5-amd64 -C /lib/modules/4.9.0-5-amd64/build M=/var/lib/dkms/falco/0.8.1/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.9.0-5-amd64 (x86_64)
Consult /var/lib/dkms/falco/0.8.1/build/make.log for more information.
* Trying to load a system falco-probe, if present
* Trying to load a dkms falco-probe, if present
* Trying to find precompiled falco-probe for 4.9.0-5-amd64
Found kernel config at /host/boot/config-4.9.0-5-amd64
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.8.1-x86_64-4.9.0-5-amd64-ee001c6bfb0cedce69a9bb978ba15926.ko
Download failed, consider compiling your own falco-probe and loading it or getting in touch with the sysdig community
Sat Jan 13 05:44:59 2018: Falco initialized with configuration file /etc/falco/falco.yaml
Sat Jan 13 05:44:59 2018: Parsed rules from file /etc/falco/falco_rules.yaml
Sat Jan 13 05:44:59 2018: Parsed rules from file /etc/falco/falco_rules.local.yaml
Sat Jan 13 05:44:59 2018: Unable to load the driver. Exiting.
Sat Jan 13 05:44:59 2018: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco-probe module is loaded.. Exiting.

What steps can I take to work around the issue or resolve the issue?

**Comment by stevemcquaid** [comment]
:+1:

**Comment by stevemcquaid** [comment]
This was also reported in #333. I ran into the same thing but was able to use thesysdig/falco:dev image in the [daemonset resource definition](https://github.com/draios/falco/blob/dev/examples/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml#L19) that fixes this bug.

**Comment by mstemm** [comment]
Looks like the same thing. I'll close this and we plan on having a falco release shortly so the fix will be available in the stable image.
