### ISSUE TITLE
Missing 0.9.0 docker image in dockerhub

### ISSUE THREAD

**Issue by MQasimSarfraz** [draios/falco#328]
Please add `0.9.0` docker image to dockerhub, https://hub.docker.com/r/sysdig/falco/

**Comment by mstemm** [comment]
Ok, fixed! Now available at https://hub.docker.com/r/sysdig/falco/tags. Thanks for pointing it out, and sorry for the missing tag.

**Comment by MQasimSarfraz** [comment]
@mstemm thanks for quick response! :+1:
