### ISSUE TITLE
Unable to run falco as a container on Ubuntu 16.04

### ISSUE THREAD

**Issue by wheelybird** [draios/falco#332]
Hi.
I can't get falco running as a container on Ubuntu 16.04.  It can't write to /lib/modules to compile the module (which I understand is intentional), but it also can't download a pre-compiled module from S3.
Trying to download the module manually results in 'Access denied'.

Do you have any ideas on how I can get falco running?

>Status:
>
> Downloaded newer image for sysdig/falco:latest
>* Setting up /usr/src links from host
>* Unloading falco-probe, if present
>rmmod: ERROR: Module falco_probe is not currently loaded
>* Running dkms install for falco
>
>Kernel preparation unnecessary for this kernel.  Skipping...
>
>Building module:
>cleaning build area...
>make -j4 KERNELRELEASE=4.4.0-116-generic -C /lib/modules/4.4.0-116-generic/build M=/var/lib/dkms/falco/0.9.0/build....
>cleaning build area...
>
>DKMS: build completed.
>
>falco-probe.ko:
>Running module version sanity check.
> - Original module
>   - No original module exists within this kernel
> - Installation
>   - Installing to /lib/modules/4.4.0-116-generic/kernel/extra/
>mkdir: cannot create directory '/lib/modules/4.4.0-116-generic/kernel/extra': Read-only file system
>cp: cannot create regular file '/lib/modules/4.4.0-116-generic/kernel/extra/falco-probe.ko': No such file or directory
>
>depmod....
>
>DKMS: install completed.
>* Trying to load a dkms falco-probe, if present
>* Trying to load a system falco-probe, if present
>* Trying to find precompiled falco-probe for 4.4.0-116-generic
>Found kernel config at /host/boot/config-4.4.0-116-generic
>* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.9.0-x86_64-4.4.0-116-generic-844c262ad06554a45f6d1d87e99d626d.ko
>Download succeeded, loading module
>insmod: ERROR: could not insert module /root/.sysdig/falco-probe-0.9.0-x86_64-4.4.0-116-generic-844c262ad06554a45f6d1d87e99d626d.ko: Invalid module format
>Wed Feb 28 16:11:47 2018: Falco initialized with configuration file /etc/falco/falco.yaml
>Wed Feb 28 16:11:47 2018: Parsed rules from file /etc/falco/falco_rules.yaml
>Wed Feb 28 16:11:47 2018: Parsed rules from file /etc/falco/falco_rules.local.yaml
>Wed Feb 28 16:11:47 2018: Unable to load the driver. Exiting.
>Wed Feb 28 16:11:47 2018: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco-probe module is loaded.. Exiting.

**Comment by mfdii** [comment]
This was also reported in #333. Please try the sysdig/falco:dev image that fixes this bug. If this doesn't fix the problem, please reopen this issue.
