### ISSUE TITLE
Visualization with grafana for Falco 

### ISSUE THREAD

**Issue by kratos81** [draios/falco#420]
I'd like to know if there is any support/integration of falco with grafana .  If so , is there any documentation /wiki you can point me to in order to achieve this.   We are trying to install falco as a daemonset in Kubernetes and  already have Prometheus and grafana set up in the cluster. Initially , we had the alerts go to a slack channel but we would prefer to have this integrated with grafana.  I have explored the EFK stack but that would require the additional overhead managing Elasticsearch

**Comment by henridf** [comment]
@kratos81 there isn't currently any support for exposing metrics, but I filed #421 to track this.

**Comment by kratos81** [comment]
Thank you @henridf
