### ISSUE TITLE
Consider documenting comparisons to alternatives (e.g. auditd), vis mandatory controls

### ISSUE THREAD

**Issue by jcmcken** [draios/falco#77]
It may be a useful exercise to document some comparisons between `falco` and something like `auditd`. For example, `auditd` also is built around the concept of identifying syscall conditions and logging the results (or otherwise delivering them somewhere). It can also be configured to halt the system if triggered events cannot be delivered to their destination, which is certainly a highly-valued feature when you want to make sure an adversary isn't trying to cover their tracks (e.g. either stopping auditing or redirecting events to a blackhole, etc.). Clearly `falco` seems a bit more expressive and user-friendly than `auditd` from a configuration and usability point-of-view, but what types of mandatory controls can be configured or introduced to ensure that what you see in your audits is actually what happened?

**Comment by mstemm** [comment]
Thanks, that's really good feedback. We might end up doing this comparison on the falco website (http://www.sysdig.org/falco/) instead of in the github-level documentation, but we do want to show how this compares to existing tools.

**Comment by ikoniaris** [comment]
+1

**Comment by cnwatu** [comment]
+1

**Comment by mstemm** [comment]
We've written a blog post that compares Falco, Auditd, SELinux, AppArmor, and other similar tools. It's available [here](https://sysdig.com/blog/selinux-seccomp-falco-technical-discussion/). Hopefully this will help!
