### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [draios/falco#79]
Some parameters (like "[${SYSDIG_DIR}/driver](https://github.com/draios/falco/blob/acfa8e768669952cd7f24e02f67dca7bdd906193/CMakeLists.txt#L183)" and "[${PROJECT_SOURCE_DIR}/scripts/debian/falco](https://github.com/draios/falco/blob/cfc89127e75c820ebcaa6c8b7547cb0e64411842/scripts/CMakeLists.txt#L1)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](https://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes. "CMake splits arguments unless you use quotation marks or escapes.").

**Comment by mstemm** [comment]
Thanks, fix otw.
