### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [draios/falco#80]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") in [the function "falco_init"](https://github.com/draios/falco/blob/b5055e34affe6f117331468e7ccfe6c89ea506cf/userspace/falco/falco.cpp#L497 "Update candidate: falco_init()").

**Comment by mstemm** [comment]
Thanks, fix otw.

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for further source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?
